version: '3.8'

services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: scraper-api-image:latest
    hostname: scraper-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
